$(function () {
    /**
     * 计算各个板块的高度
     */
    var bodyHeight = $(window).height();
    var headerHeight = $(".header").outerHeight(true);
    var footerHeight = $(".footer").outerHeight(true);
    var contentWrapper = bodyHeight - headerHeight - footerHeight;
    $(".contentWrapper").height(contentWrapper);

    /**
     * 设置通用的header和footer
     */
    var header = '';
    var footer = '';
    header += '       <nav class="nav-top navbar">';
    header += '               <div class="container-fluid">';
    /**
     * 手机端的样式
     */
    header += '               <div class="navbar-header">';
    header += '               <div class="nav-top-mobile">';
    header += '               <div class="mobile-user">';
    header += '               <ul>';
    header += '               <li class="dropdown">';
    header += '               <a href="#" class="mobile-user-profile dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i></a>';
    header += '           <ul class="mobile-user-dropdown dropdown-menu animated fadeInDown">';
    header += '               <li><a href="my-profile.html">个人主页</a></li>';
    header += '           <li role="separator" class="divider"></li>';
    header += '               <li><a href="lock.html"><i class="fa fa-lock" aria-hidden="true"></i>锁定</a></li>';
    header += '          <li><a href="log-in.html"><i class="fa fa-sign-out" aria-hidden="true"></i>注销</a>';
    header += '           </li>';
    header += '           </ul>';
    header += '           </li>';
    header += '           </ul>';
    header += '           </div>';
    header += '           <div class="mobile-search">';
    header += '               <a href="#" class="mobile-search-trigger" role="button"><i class="fa fa-search" aria-hidden="true"></i></a>';
    header += '           <div class="mobile-search-active animated fadeInDown">';
    header += '               <form class="mobile-search-box">';
    header += '               <i class="glyphicon glyphicon-search"></i>';
    header += '               <input class="mobile-search-input" autofocus type="text" spellcheck="false" placeholder="搜索...">';
    header += '               <button type="button" class="close">';
    header += '               <span>&times;</span>';
    header += '           </button>';
    header += '           </form>';
    header += '           </div>';
    header += '           </div>';
    header += '           </div>';
    header += '           <div class="logo ">';
    header += '               <a class="navbar-brand" href="index.html">';
    header += '               <img src="img/logo.png" alt="Rocket Logo">';
    header += '               <span>XXX花店</span>';
    header += '               <small class="hidden-xs">Raise your standards</small>';
    header += '           </a>';
    header += '           </div>';
    header += '           </div>';
    header += '           <div class="collapse navbar-collapse hidden-xs">';
    header += '               <ul class="user-profile nav navbar-nav navbar-right">';
    header += '               <li class="dropdown">';
    header += '               <a class="user-block dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">';
    header += '               <span class="user-name">您好，XXX</span>';
    header += '           <span class="caret"></span>';
    header += '               <img src="img/users/user01.jpg" alt="User image">';
    header += '               </a>';
    header += '               <ul class="user-profile-dropdown dropdown-menu animated fadeInDown">';
    header += '               <li>';
    header += '               <a href="my-profile.html"><i class="fa fa-user" aria-hidden="true"></i>个人主页</a>';
    header += '           </li>';
    header += '           <li role="separator" class="divider"></li>';
    header += '               <li>';
    header += '               <a href="lock.html"><i class="fa fa-lock" aria-hidden="true"></i>锁定</a>';
    header += '           </li>';
    header += '           <li>';
    header += '           <a href="log-in.html"><i class="fa fa-sign-out" aria-hidden="true"></i>注销</a>';
    header += '           </li>';
    header += '           </ul>';
    header += '           </li>';
    header += '           </ul>';
    header += '           <form class="nav-search">';
    header += '               <input class="nav-search-input" type="text" spellcheck="false" placeholder="搜索...">';
    header += '               <i class="glyphicon glyphicon-search" aria-hidden="true"></i>';
    header += '               </form>';
    header += '               </div>';
    header += '               </div>';
    header += '               </nav>';
    $(".header").html(header);
    footer += '        <footer>';
    footer += '            <div class="nav-bottom navbar nav-fixed">';
    footer += '                <div class="row">';
    footer += '                <a class="col-xs-3 nav-dash" href="index.html">';
    footer += '                <i class="fa fa-rocket" aria-hidden="true"></i><br>';
    footer += '                <span class="hidden-xs">Dashboard</span>';
    footer += '                </a>';
    footer += '                <a class="col-xs-3 nav-myProfile" href="my-profile.html">';
    footer += '                <i class="fa fa-user" aria-hidden="true"></i><br>';
    footer += '                <span class="hidden-xs">My Profile</span>';
    footer += '            </a>';
    footer += '            <a class="col-xs-3 nav-users" href="users.html">';
    footer += '                <i class="fa fa-users" aria-hidden="true"></i><br>';
    footer += '                <span class="hidden-xs">Users</span>';
    footer += '                </a>';
    footer += '                <a class="col-xs-3 nav-more" href="edit-profile.html">';
    footer += '                <i class="fa fa-plus" aria-hidden="true"></i><br>';
    footer += '                <span class="hidden-xs">More</span>';
    footer += '                </a>';
    footer += '                </div>';
    footer += '                </div>';
    footer += '                <div id="box" class="nav-moreBox animated fadeInDown">';
    footer += '                <div class="moreBox-item" data-toggle="collapse" data-target="#uiElements">';
    footer += '                <i class="fa fa-desktop" aria-hidden="true"></i>';
    footer += '            UI Elements';
    footer += '            <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>';
    footer += '                <div id="uiElements" class="collapse">';
    footer += '                <ul>';
    footer += '                <li><a href="alerts.html">Alerts</a></li>';
    footer += '            <li><a href="animations.html">Animations</a></li>';
    footer += '            <li><a href="buttons.html">Buttons</a></li>';
    footer += '            <li><a href="grid-system.html">Grid System</a></li>';
    footer += '            <li><a href="pagination.html">Pagination</a></li>';
    footer += '            <li><a href="progress-bars.html">Progress Bars</a></li>';
    footer += '            <li><a href="typography.html">Typography</a></li>';
    footer += '            </ul>';
    footer += '            </div>';
    footer += '            </div>';
    footer += '            </div>';
    footer += '            </div>';
    footer += '            </footer>';
    $(".footer").html(footer);
});